default:
  aws_access_key_id: 'AKIAJH35E2YQNTDB4SQQ'       # required
  aws_secret_access_key: '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'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'
